# Generated by Django 4.2.10 on 2024-03-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_metrices_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrices',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
