# Generated by Django 4.2.10 on 2024-03-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_metrices_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrices',
            old_name='active',
            new_name='is_active',
        ),
    ]
