# Generated by Django 5.0.6 on 2024-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
