# Generated by Django 5.0.6 on 2025-01-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='missed_hours',
            field=models.DurationField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='redeemed_hours',
            field=models.DurationField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='remaining_hours',
            field=models.DurationField(default=0, null=True),
        ),
    ]
