# Generated by Django 5.0.6 on 2025-01-21 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_alter_worklog_missed_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='missed_hours',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='redeemed_hours',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='remaining_hours',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
