# Generated by Django 5.0.6 on 2024-10-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0009_alter_leaves_leave_type_alter_leaves_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leaves_types',
            },
        ),
    ]
