# Generated by Django 5.0.6 on 2024-05-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leaves_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('CASUAL', 'casual'), ('SICK', 'sick')], default='PENDING'),
        ),
    ]
