# Generated by Django 5.0.6 on 2024-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaves_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], default='PENDING'),
        ),
    ]
