# Generated by Django 5.0.6 on 2024-05-31 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_alter_leaves_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
