# Generated by Django 5.0.6 on 2024-05-31 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leaves_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
