# Generated by Django 5.0.6 on 2024-07-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_leaves_updated_at_alter_leaves_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'casual'), ('SICK', 'sick')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=50),
        ),
    ]
