# Generated by Django 5.0.6 on 2025-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_alter_leaves_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
