# Generated by Django 5.0.6 on 2025-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_alter_leaves_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
