# Generated by Django 5.0.6 on 2025-01-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="timestap",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="poll",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
