# Generated by Django 5.0.6 on 2024-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
