# Generated by Django 5.0.6 on 2024-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_in_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_in_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
