# Generated by Django 5.0.6 on 2024-07-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_punch_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
