# Generated by Django 5.0.6 on 2024-11-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
