# Generated by Django 5.0.6 on 2025-01-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours_worked',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
