# Generated by Django 5.0.6 on 2025-01-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='hours_worked',
        ),
    ]
