# Generated by Django 5.0.6 on 2025-01-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
