# Generated by Django 5.0.6 on 2025-01-21 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
